Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:
1. Length:

– Convert meters (m) to feet (ft).

– Convert feet (ft) to meters (m).
2. Weight:

– Convert kilograms (kg) to pounds (lbs).

– Convert pounds (lbs) to kilograms (kg).
3. Volume:

– Convert liters (L) to gallons (gal).

– Convert gallons (gal) to liters (L).

In [ ]:
def convert_length(value, unit):
    if unit == 'm':
        return f"{value * 3.28084:.2f} ft"
    elif unit == 'ft':
        return f"{value / 3.28084:.2f} m"
    else:
        raise ValueError("Unsupported length unit.")

def convert_weight(value, unit):
    if unit == 'kg':
        return f"{value * 2.20462:.2f} lbs"
    elif unit == 'lbs':
        return f"{value / 2.20462:.2f} kg"
    else:
        raise ValueError("Unsupported weight unit.")

def convert_volume(value, unit):
    if unit == 'L':
        return f"{value * 0.264172:.2f} gal"
    elif unit == 'gal':
        return f"{value / 0.264172:.2f} L"
    else:
        raise ValueError("Unsupported volume unit.")

def main():
    while True:
        print("\nUnit Conversion Program:")
        print("1. Length (m <-> ft)")
        print("2. Weight (kg <-> lbs)")
        print("3. Volume (L <-> gal)")
        print("4. Exit")

        choice = input("Choose a conversion type (1-4): ").strip()
        if choice == '4':
            print("Exiting program. Goodbye!")
            break

        if choice not in ('1', '2', '3'):
            print("Invalid choice. Please select a number between 1 and 4.")
            continue

        value = input("Enter the value to convert: ").strip()
        if not value.replace('.', '', 1).isdigit():
            print("Error: Invalid input. Please enter a numeric value.")
            continue

        value = float(value)

        unit = input("Enter the unit: ").strip()  # No .lower() to keep 'L' uppercase


        try:
            if choice == '1':
                print("Converted value:", convert_length(value, unit))
            elif choice == '2':
                print("Converted value:", convert_weight(value, unit))
            elif choice == '3':
                print("Converted value:", convert_volume(value, unit))
        except ValueError as e:
            print("Error:", e)

if __name__ == "__main__":
    main()



Unit Conversion Program:
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
4. Exit
Choose a conversion type (1-4): 1
Enter the value to convert: 55
Enter the unit: ft
Converted value: 16.76 m

Unit Conversion Program:
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
4. Exit
Choose a conversion type (1-4): 4
Exiting program. Goodbye!


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

6CS012 Worksheet - 0 Siman Giri

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
"""Returns the sum if the given list of numbers.
:param numbers: A list of numberical values.
:return: Sim of the numbers.
"""
def calculate_sum(numbers):
  return sum(numbers)

"""Returns the average of the given list of numbers.
:param numbers: A list of numberical values.
:return: Average of the numbers.
"""
def calculate_average(numbers):
  return sum(numbers)/len(numbers) if numbers else 0

"""Returns the maximum of the given list of numbers.
:param numbers: A list of numberical values.
:return: Maximal of the numbers.
"""
def find_maximum(numbers):
  return max(numbers)

"""Returns the minimum of the given list of numbers.
:param numbers: A list of numberical values.
:return: minimum of the numbers.
"""
def find_minimum(numbers):
  return min(numbers)

def main():
  while True:
    print("\n Mathemathical operations on a List of Numbers")
    print("1. sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")
    print("5. Exit")

    choice = input("Choose an operation (1-5): ").strip()

    if choice == '5':
      print("Exiting program. Goodbye!")
      break

    if choice not in ('1', '2', '3', '4'):
      print("Invalid choicve. Please select a number between 1 and 5.")
      continue

    numbers_input = input("Enter a list of numbers separated by spaces:").strip()

    try:
      numbers = [float(num) for num in numbers_input.split()]
      if not numbers:
        raise ValueError("The list numbers cannot be empty.")
    except ValueError:
      print("Error: Invalid input. Please enter a valid list of numbers.")
      continue

    if choice == '1':
      print("Sum:", calculate_sum(numbers))
    elif choice == '2':
      print("Average:", calculate_average(numbers))
    elif choice == '3':
      print("Maximum:", find_maximum(numbers))
    elif choice == '4':
      print("Minimum:", find_minimum(numbers))

if __name__ == "__main__":
  main()



 Mathemathical operations on a List of Numbers
1. sum
2. Average
3. Maximum
4. Minimum
5. Exit
Choose an operation (1-5): 4
Enter a list of numbers separated by spaces:5 2 10 5 6
Minimum: 2.0

 Mathemathical operations on a List of Numbers
1. sum
2. Average
3. Maximum
4. Minimum
5. Exit
Choose an operation (1-5): 5
Exiting program. Goodbye!


4.2 Exercise on List Manipulation:

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
  return lst[::2]

example_list = [1, 2, 3, 4, 5, 6]
print(extract_every_other(example_list))

[1, 3, 5]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
  return lst[start:end+1]

lst = [1,2,3,4,5,6]
start = 2
end = 4
result = get_sublist(lst, start, end)
print(result)

[3, 4, 5]


Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
  return lst[::-1]

lst = [1,2,3,4,5]
result = reverse_list(lst)
print(result)

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
  return lst[1:-1]
lst = [1,2,3,4,5]
result = remove_first_last(lst)
print(result)

[2, 3, 4]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst,n):
  return lst[:n]

my_list = [1,2,3,4,5]
n = 3
first_n_elements = get_first_n(my_list, n)
print(first_n_elements)

[1, 2, 3]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
  return lst[-n:]

mi_list = [1,2,3,4,5]
n = 2
last_n_elements = get_last_n(mi_list, n)
print(last_n_elements)


[4, 5]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
  return lst[-2 :: -2]

my_list = [1,2,3,4,5,6]
result = reverse_skip(my_list)
print(result)

[5, 3, 1]


4.3 Exercise on Nested List:

1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
  flattened_list = []
  for item in lst:
     if isinstance(item, list):
      flattened_list.extend(flatten(item))
     else:
      flattened_list.append(item)
  return flattened_list
nested_list = [[1,2],[3,4],[5]]
flattened_list = flatten(nested_list)
print(flattened_list)

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):

  element = lst
  for index in indices:
    element = element[index]
  return element

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1,2]
element = access_nested_element(lst,indices)
print(element)

6


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
  total_sum = 0
  for item in lst:
    if isinstance(item, list):
      total_sum += sum_nested(item)
    elif isinstance(item, (int, float)):
      total_sum+=item
  return total_sum

nested_list = [[1, 2], [3, [4, 5]], 6]
total_sum = sum_nested(nested_list)
print(total_sum)



21


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
   max_element = float('-inf')  # Initialize with negative infinity

   for item in lst:
    if isinstance(item, list):
      max_element = max(max_element, find_max(item))  # Recursive call
    elif isinstance(item, (int, float)):
      max_element = max(max_element, item)

   return max_element

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
max_element = find_max(nested_list)
print(max_element)  # Output: 6


6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:

def count_occurrences(lst, elem):
  count = 0
  for item in lst:
    if isinstance(item, list):
      count += count_occurrences(item, elem)
    elif item == elem:
      count += 1
  return count

# Example usage
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
occurrences = count_occurrences(lst, elem)
print(occurrences)  # Output: 3

3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
  flattened_list = []
  for item in lst:
    if isinstance(item, list):
      flattened_list.extend(deep_flatten(item))
    else:
      flattened_list.append(item)
  return flattened_list

lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
flattened_list = deep_flatten(lst)
print(flattened_list)

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
  total_sum = 0
  count = 0
  for item in lst:
    if isinstance(item, list):
      for element in item:
        if isinstance(element, (int, float)):
          total_sum += element
          count += 1
    elif isinstance(item, (int, float)):
      total_sum += item
      count += 1
  return total_sum / count if count else 0

lst = [[1, 2], [3, 4], [5, 6]]
average = average_nested(lst)
print(average)

3.5


Problem - 1: Array Creation:

Complete the following Tasks:

1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2X2.
empty_array = np.empty((2, 2))

# 2. Initialize an all one array with size 4X2.
ones_array = np.ones((4, 2))

# 3. Return a new array of given shape and type, filled with fill value.
shape = (3, 3)
fill_value = 7
full_array = np.full(shape, fill_value)

# 4. Return a new array of zeros with the same shape and type as a given array.
example_array = np.array([[1, 2], [3, 4]], dtype=int)
zeros_array = np.zeros_like(example_array)

# 5. Return a new array of ones with the same shape and type as a given array.
ones_like_array = np.ones_like(example_array)

# 6. For an existing list new_list = [1, 2, 3, 4] convert to a numpy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)

# Print the results (optional)
print("1. Empty Array:\n", empty_array)
print("\n2. Ones Array:\n", ones_array)
print("\n3. Full Array:\n", full_array)
print("\n4. Zeros Like Array:\n", zeros_array)
print("\n5. Ones Like Array:\n", ones_like_array)
print("\n6. Numpy Array from List:\n", numpy_array)


1. Empty Array:
 [[5.27986577e-316 0.00000000e+000]
 [5.73116149e-322 0.00000000e+000]]

2. Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Like Array:
 [[0 0]
 [0 0]]

5. Ones Like Array:
 [[1 1]
 [1 1]]

6. Numpy Array from List:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49.
array1 = np.arange(10, 50)

# 2. Create a 3x3 matrix with values ranging from 0 to 8.
array2 = np.arange(9).reshape(3, 3)

# 3. Create a 3x3 identity matrix.
array3 = np.eye(3)

# 4. Create a random array of size 30 and find the mean.
array4 = np.random.random(30)
mean_array4 = array4.mean()

# 5. Create a 10x10 array with random values and find min/max.
array5 = np.random.random((10, 10))
min_array5 = array5.min()
max_array5 = array5.max()

# 6. Create a zero array of size 10 and replace 5th element with 1.
array6 = np.zeros(10)
array6[4] = 1  # Remember, Python indexing starts at 0

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0].
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]

# 8. Create a 2d array with 1 on border and 0 inside.
array8 = np.ones((5, 5))  # Example size, adjust as needed
array8[1:-1, 1:-1] = 0

# 9. Create an 8x8 matrix with a checkerboard pattern.
array9 = np.zeros((8, 8), dtype=int)
array9[::2, 1::2] = 1
array9[1::2, ::2] = 1


print("\n1.", array1)

print("\n2.", array2)

print("\n3.", array3)

print("\n4. Mean:", mean_array4)

print("\n5. Min:", min_array5, "Max:", max_array5)

print("\n6.", array6)

print("\n7.", reversed_arr)

print("\n8.", array8)
print("\n9.", array9)


1. [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean: 0.5213346835047382

5. Min: 0.00939210677864899 Max: 0.9872088312443669

6. [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. [0, 4, 0, 0, 2, 1]

8. [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays (x and y)
add_result = x + y

# 2. Subtract the two arrays (x and y)
subtract_result = x - y

# 3. Multiply the array x by an integer (e.g., 3)
multiply_result = x * 3

# 4. Find the square of each element of the array x
square_result = x ** 2

# 5. Find the dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

# 6. Concatenate
concat_xy_row = np.concatenate((x, y), axis=0)  # Along row (axis=0)
concat_vw_col = np.vstack((v, w))       # Along column (equivalent to axis=0 for 1D arrays)


# 7. Concatenate x and v (will result in an error)
# concat_xv = np.concatenate((x, v), axis=0)  # Uncomment to see the error

# Explanation of the error in step 7:
# The error occurs because x has shape (2, 2) and v has shape (2,).
# np.concatenate requires arrays to have the same number of dimensions
# along the concatenation axis (axis=0 in this case).

# To fix the error:

# Option 1: Reshape v to have 2 dimensions:
v_reshaped = v.reshape(1, 2) # Reshape to (1,2)
concat_xv = np.concatenate((x,v_reshaped), axis=0)

# Print the results (optional - uncomment to see outputs)
print("1. Addition:\n", add_result)
print("\n2. Subtraction:\n", subtract_result)
print("\n3. Multiplication:\n", multiply_result)
print("\n4. Square:\n", square_result)
print("\n5. Dot Products: vw =", dot_vw, ", xv =", dot_xv, ", xy =\n", dot_xy)
print("\n6. Concatenation: xy (row) =\n", concat_xy_row, ", vw (col) =\n", concat_vw_col)
print("\n7. Concatenation (after reshape): xv =\n", concat_xv)

1. Addition:
 [[ 6  8]
 [10 13]]

2. Subtraction:
 [[-4 -4]
 [-4 -3]]

3. Multiplication:
 [[ 3  6]
 [ 9 15]]

4. Square:
 [[ 1  4]
 [ 9 25]]

5. Dot Products: vw = 219 , xv = [29 77] , xy =
 [[19 22]
 [50 58]]

6. Concatenation: xy (row) =
 [[1 2]
 [3 5]
 [5 6]
 [7 8]] , vw (col) =
 [[ 9 10]
 [11 12]]

7. Concatenation (after reshape): xv =
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)  # Calculate the inverse of A
identity_matrix = np.dot(A, A_inv)  # Multiply A by its inverse
print(np.allclose(identity_matrix, np.eye(2)))  # Check if it's close to the identity matrix (True)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print(np.array_equal(AB, BA))  # Check if AB is equal to BA (False)

# 3. Prove (AB)^T = B^T A^T
AB_transpose = np.transpose(AB)
B_transpose_A_transpose = np.dot(np.transpose(B), np.transpose(A))
print(np.array_equal(AB_transpose, B_transpose_A_transpose))  # Check if (AB)^T = B^T A^T (True)

# Solving the system of linear equations
# Represent the equations in matrix form: AX = B
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Solve for X using the inverse method
X = np.linalg.solve(A, B)  # Using np.linalg.solve
print("Solution using np.linalg.solve:", X)

# Solve for X using np.linalg.inv
X_inv = np.dot(np.linalg.inv(A), B)  # Using np.linalg.inv
print("Solution using np.linalg.inv:", X_inv)

"""Explore more about 'linalg' function of NumPy:
The 'linalg' submodule in NumPy provides functions for linear algebra operations,
including solving systems of equations, finding eigenvalues and eigenvectors,
calculating matrix decompositions (like SVD, QR), and more."""


True
False
True
Solution using np.linalg.solve: [ 2.  1. -2.]
Solution using np.linalg.inv: [ 2.  1. -2.]


1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
import numpy as np

# Create two lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Element-wise addition using Python lists
start_time = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken using Python lists: {list_time:.4f} seconds")

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Element-wise addition using NumPy arrays
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken using NumPy arrays: {array_time:.4f} seconds")

Time taken using Python lists: 0.0685 seconds
Time taken using NumPy arrays: 0.0045 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
import numpy as np

# Create two lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Element-wise multiplication using Python lists
start_time = time.time()
result_list = [x * y for x, y in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken using Python lists: {list_time:.4f} seconds")

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Element-wise multiplication using NumPy arrays
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken using NumPy arrays: {array_time:.4f} seconds")

Time taken using Python lists: 0.0667 seconds
Time taken using NumPy arrays: 0.0047 seconds


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
import numpy as np

# Create two lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Dot product using Python lists
start_time = time.time()
dot_product_list = sum(x * y for x, y in zip(list1, list2))
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken using Python lists: {list_time:.4f} seconds")

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Dot product using NumPy arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken using NumPy arrays: {array_time:.4f} seconds")

Time taken using Python lists: 0.1125 seconds
Time taken using NumPy arrays: 0.0017 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Create two matrices of size 1000x1000 using Python lists
matrix1_list = [[1 for _ in range(1000)] for _ in range(1000)]
matrix2_list = [[2 for _ in range(1000)] for _ in range(1000)]

# Matrix multiplication using Python lists
start_time = time.time()

result_list = [[sum(a * b for a, b in zip(row_a, col_b))
                  for col_b in zip(*matrix2_list)]
                 for row_a in matrix1_list]

end_time = time.time()
list_time = end_time - start_time
print(f"Time taken using Python lists: {list_time:.4f} seconds")

# Create two matrices of size 1000x1000 using NumPy arrays
matrix1_array = np.ones((1000, 1000))
matrix2_array = np.full((1000, 1000), 2)  # Fill with 2

# Matrix multiplication using NumPy arrays
start_time = time.time()
result_array = np.dot(matrix1_array, matrix2_array)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken using NumPy arrays: {array_time:.4f} seconds")

Time taken using Python lists: 75.7446 seconds
Time taken using NumPy arrays: 0.1409 seconds
